site_name: 2020_5DI_Team1
nav:
    - 'Project Charter': 'vspc.md'
    - 'Elevator Statement': 'elevatorSpeech.md'
    - 'Software Requirements Specification': 'srs.md'
    - 'Software Project Management plan': 'spmp.md'
   
    
theme:
    name: readthedocs

