site_name: 2020_5DI_Team1
nav:
    - 'Project Charter': 'vspc.md'
    - 'Elevator Statement': 'elevatorSpeech.md'
    - 'Software Requirements Specification': 'srs.md'
    - 'Software Project Management plan': 'spmp.md'
    - 'releasePlan': 'releasePlan.md'
    - 'iterationPlan': 'iterationPlan.md'
    - 'architectureAndDesign': 'architectureAndDesign.md'
    - 'codingStandards': 'codingStandards.md'
    - 'successCriteria': 'successCriteria.md'
    - 'systemDocumentation': 'systemDocumentation.md'
    - 'testPlan': 'testPlan.md'
    - 'userGuide': 'userGuide.md'
    - 'testCaseSpecification': 'testCaseSpecification.md'
    - 'memorandumOfUnderstanding': 'memorandumOfUnderstanding.md'
   
    
theme:
    name: readthedocs

