site_name: 2020_5DI_Team1
nav:
    - 'Project Charter': 'vspc.md'
    - 'Elevator Statement': 'elevatorSpeech.md'
    - 'Software Requirements Specification': 'srs.md'
    - 'Software Project Management plan': 'spmp.md'
    - 'releasePlan': 'releasePlan.md'
    - 'iterationPlan': 'iterationPlan.md'
    - 'architectureAndDesign': 'architectureAndDesign.md'
    - 'codingStandards': 'codingStandards.md'
    - 'successCriteria': 'successCriteria.md'
    - 'systemDocumentation': 'systemDocumentation.md'
    - 'testPlan': 'testPlan.md'
    - 'userGuide': 'userGuide.md'
    - 'testCaseSpecification': 'testCaseSpecification.md'
    - 'memorandumOfUnderstanding': 'memorandumOfUnderstanding.md'
    - 'releasePlanPDF': 'releasePlan.pdf'
    - 'iterationPlanPDF': 'iterationPlan.pdf'
    - 'architectureAndDesignPDF': 'architectureAndDesign.pdf'
    - 'codingStandardsPDF': 'codingStandards.pdf'
    - 'successCriteriaPDF': 'successCriteria.pdf'
    - 'systemDocumentationPDF': 'systemDocumentation.pdf'
    - 'testPlanPDF': 'testPlan.pdf'
    - 'userGuidePDF': 'userGuide.pdf'
    - 'testCaseSpecificationPDF': 'testCaseSpecification.pdf'
    - 'memorandumOfUnderstandingPDF': 'memorandumOfUnderstanding.pdf'
   
    
theme:
    name: readthedocs

